import {
  pgTable,
  serial,
  text,
  real,
  boolean,
  timestamp,
  jsonb,
  integer,
} from "drizzle-orm/pg-core";

export const btcusdSnapshotsTable = pgTable("btcusd_snapshots", {
  id: serial("id").primaryKey(),
  snapshotAt: timestamp("snapshot_at").notNull().defaultNow(),
  price: real("price").notNull(),
  open: real("open"),
  high: real("high"),
  low: real("low"),
  volume: real("volume"),
  priceChange: real("price_change"),
  isSpike: boolean("is_spike").notNull().default(false),
  rsi14: real("rsi14"),
  ema9: real("ema9"),
  ema21: real("ema21"),
  ema50: real("ema50"),
  ema200: real("ema200"),
  macdLine: real("macd_line"),
  macdSignal: real("macd_signal"),
  macdHistogram: real("macd_histogram"),
  bbUpper: real("bb_upper"),
  bbMiddle: real("bb_middle"),
  bbLower: real("bb_lower"),
  atr14: real("atr14"),
  trend: text("trend"),
  supportLevel: real("support_level"),
  resistanceLevel: real("resistance_level"),
  bbWidth: real("bb_width"),
  rsiSignal: text("rsi_signal"),
  macdSignalType: text("macd_signal_type"),
  emaAlignment: text("ema_alignment"),
});

export const btcusdBrainTable = pgTable("btcusd_brain", {
  id: serial("id").primaryKey(),
  category: text("category").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  confidence: real("confidence").notNull().default(0.5),
  usageCount: integer("usage_count").notNull().default(0),
  lastValidated: timestamp("last_validated"),
  isActive: boolean("is_active").notNull().default(true),
  sourceQuestion: text("source_question"),
  marketConditionTags: text("market_condition_tags"),
  decayWeight: real("decay_weight").notNull().default(1.0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const btcusdQuestionsLogTable = pgTable("btcusd_questions_log", {
  id: serial("id").primaryKey(),
  question: text("question").notNull(),
  questionHash: text("question_hash").notNull().unique(),
  answer: text("answer"),
  quality: real("quality"),
  savedToBrain: boolean("saved_to_brain").notNull().default(false),
  marketContext: jsonb("market_context"),
  askedAt: timestamp("asked_at").notNull().defaultNow(),
  answeredAt: timestamp("answered_at"),
});

export const btcusdPredictionsTable = pgTable("btcusd_predictions", {
  id: serial("id").primaryKey(),
  predictedAt: timestamp("predicted_at").notNull().defaultNow(),
  timeframe: text("timeframe").notNull(),
  direction: text("direction").notNull(),
  targetPrice: real("target_price"),
  entryLow: real("entry_low"),
  entryHigh: real("entry_high"),
  stopLoss: real("stop_loss"),
  confidence: real("confidence").notNull(),
  reasoning: text("reasoning").notNull(),
  priceAtPrediction: real("price_at_prediction").notNull(),
  indicatorsAtPrediction: jsonb("indicators_at_prediction"),
  tradingSession: text("trading_session"),
  marketRegime: text("market_regime"),
  clusterLabel: text("cluster_label"),
  predictionType: text("prediction_type").notNull().default("training"),
  verifyAt: timestamp("verify_at"),
  actualPrice: real("actual_price"),
  actualDirection: text("actual_direction"),
  isCorrect: boolean("is_correct"),
  priceDiff: real("price_diff"),
  status: text("status").notNull().default("pending"),
});

export const btcusdLearningLogTable = pgTable("btcusd_learning_log", {
  id: serial("id").primaryKey(),
  cycleAt: timestamp("cycle_at").notNull().defaultNow(),
  priceAtCycle: real("price_at_cycle"),
  questionsAsked: integer("questions_asked").notNull().default(0),
  insightsSaved: integer("insights_saved").notNull().default(0),
  predictionsChecked: integer("predictions_checked").notNull().default(0),
  wrongPredictions: integer("wrong_predictions").notNull().default(0),
  spikeDetected: boolean("spike_detected").notNull().default(false),
  summary: text("summary"),
  durationMs: integer("duration_ms"),
});
